### PR TITLE
DDL Commands - Create, Alter, Drop

### PR DESCRIPTION
**Pull request by ShreyAswal**
Milestone 2
This PR includes the following 1 concepts as mentioned in the kalvium Doc:

- DDL Commands(Data Definition Language) 

DBMS Video Explanation :

1. https://www.loom.com/share/aeee97266bb5463990caa5522f32afb5?sid=c1ab138e-bd09-4949-bd43-4ef866d409ff
2. https://www.loom.com/share/0cbedc9786f843d9abfc0e9b2eab8192?sid=25fd5f3a-87b6-4191-b37b-88eb89c42dc5
3. https://www.loom.com/share/154437d7f8a54caa8fc5998e539c956b?sid=c81f42f6-46da-46cf-9d5d-1b458759bdfc

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @ShreyAswal , Your commands and explanation are good and sufficient for self-viva.

Please, merge it now for DDL.

Thank you.

**Comment by ShreyAswal** [comment]
Hi @PRASANNAPATHI could you mention the same comment in the below PR as I made another PR for the same milestone with the same content.

 => https://github.com/kalviumcommunity/Task_Manager_and_Collaboration_Tool/pull/7

**Comment by PRASANNAPATHI** [comment]
Why you did it for twice?
Also, why you merged this PR before approval?

**Comment by PRASANNAPATHI** [comment]
Okay cool, Please be aware before merging hereafter.

**Comment by ShreyAswal** [comment]
I by mistake merged this PR before approval
I revoked the changes in another PR.
Then, I made another PR with the same concept for the approval and then to merge.

Ya, will try to not repeat this.

**Pull request merged**
