### PR TITLE
 DML commands and Advanced SQL Queries

### PR DESCRIPTION
**Pull request by ShreyAswal**
Milestone 4
This PR includes the following 2 concepts :

DML commands-select,insert,update,delete
Advanced SQL Queries - Joins, subqueries

DBMS Video Explanation :

1. https://www.loom.com/share/a0559da6ed8e4af99923d1b6d9cc294a?sid=ccad5cd2-9d2a-4941-ac73-597f8ba609d6
2. https://www.loom.com/share/16e6c218a9864844892ee9c4a055d0e2?sid=3a30f7d6-93a5-4148-9679-24cf02d7c66e
3. https://www.loom.com/share/8cac98df968140a7b98ee49178ce81c3?sid=c4101e06-28bc-4fd2-ba56-f751e76ac90c
4. https://www.loom.com/share/456074406fdb4b2f9d2c69e851c30b7e?sid=0754cef7-f8f7-47fd-bc2f-f4f26227b0ad
5. https://www.loom.com/share/adcb2b37f0e14ed092513aafbf581c51?sid=fcc46a00-c14b-47b1-aafe-4ad4c9bed345
6. https://www.loom.com/share/726783f0b99b463a91f3774ad8e7ee2e?sid=a45a714a-2e03-4f71-8387-573b82785d68

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @ShreyAswal ,

For DML, your explanation & commands are fine.

Please merge it for DML.

But wait till the other concept gets approved

**Comment by PRASANNAPATHI** [comment]
For Advanced SQL Queries - your explanation & queries are good enough.

But our minimum required no. of queries for this concept is 3.

Please, you can merge it now for Advanced SQL queries too.

If you want to score fully, then please submit one more query to meet the requirement as mentioned above.

**Comment by ShreyAswal** [comment]
Okay, @PRASANNAPATHI . As the 2nd concept(Advanced SQL Queries) is not fully implemented yet and there is only a requirement of 1 concept to be submitted for this milestone can you only consider the DML Commands as the submission for this milestone.

Then for the next milestone I can use the Advanced SQL Queries as a concept after I implement the 3rd query.
Is that fine?

**Comment by PRASANNAPATHI** [comment]
Yes @ShreyAswal , Sure.

**Pull request merged**
