### PR TITLE
Class & Objects, Encapsulation, Static member variable

### PR DESCRIPTION
**Pull request by ShreyAswal**
**Milestone 1**
This PR includes the following changes:

Added the User.h, User.cpp, Board.h and Board.cpp file with the User and Board class definition respectively.
Also I have a main.cpp file which has functions that we can call which contain object's of each of these classes. 
You can see the working through my explaination Videos linked down below.

The concepts that I have implemented on this milestone are => 

- Classes and objects
- Encapsulation and Abstraction
- Static Elements

OOPS Video Explanation :
1. https://www.loom.com/share/53b1c5c44d284f8cb7d72b1ac1e379a8?sid=e277c084-54b5-402b-83bf-bcb466fceb22
2. https://www.loom.com/share/454edbbffc094433b5286e30428963a5?sid=fc8154d2-8873-40b0-bcb2-7ab2a8a61c90
3. https://www.loom.com/share/2143b3c748004617b5852fed3e39b9ac?sid=fbb9da54-4cd3-4258-b132-eee811997331
4. https://www.loom.com/share/f47ba20bb193493db8c51ae4d4a2ade8?sid=f0148a45-350a-4c57-a66e-7aebae6a82bb
5. https://www.loom.com/share/0a4269dbe960481985a33550bfc5e416?sid=d5bcbbd5-a4ab-47cb-a138-0d99d382dfa3

### CODE REVIEW

**Comment by Tharun-kailash** [comment]
Can you go through the sample PR given in wiki and add the things specified there?

**Comment by ShreyAswal** [comment]
Hey there @Tharun-kailash , I have **updated** the above comment and made the required changes.

**Comment by Tharun-kailash** [comment]
Hey shrey,
A PR must contain only one concept. Make sure of that from the next one.

You can merge this PR!

**Comment by Shrey-Sustally** [comment]
Okay, @Tharun-kailash  will include one concept in each PR from now onwards.
Is it okay for me to merge this directly or would it be better to include this code in a CPP folder then merge it to the main branch as I am making a combined project.

**Comment by Tharun-kailash** [comment]
Include in a CPP folder and merge, Shrey.

**Comment by ShreyAswal** [comment]
Milestone 3
For this milestone the concepts =>

- Encapsulation and Abstraction
- Static Elements

are being submitted and explained.

OOPS Video Explanation :
https://www.loom.com/share/53b1c5c44d284f8cb7d72b1ac1e379a8?sid=e277c084-54b5-402b-83bf-bcb466fceb22
https://www.loom.com/share/454edbbffc094433b5286e30428963a5?sid=fc8154d2-8873-40b0-bcb2-7ab2a8a61c90
https://www.loom.com/share/2143b3c748004617b5852fed3e39b9ac?sid=fbb9da54-4cd3-4258-b132-eee811997331



Note: These are the same videos(first 3 videos) from the 1st comment above in this Pull Request. They contain the explanation of the two concepts that I will be submitting for the 3rd PR.
You have already approved the code and video explanation in the above comment. 
This comment is to inform you that in the first milestone I had only submitted the 1st concept 
Classes and objects in the livebook submission.
For the 3rd milestone I will be submitting the other two concepts in the livebook. Which are =>
- Encapsulation and Abstraction
- Static Elements.

**Comment by th3c0d3br34ker** [comment]
hey @ShreyAswal please raise a separate PR. you may refer [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

once you do that, please re-submit.

**Comment by ShreyAswal** [comment]
Hi, @th3c0d3br34ker I have raised another PR after having a call with @Tharun-kailash and resubmitted that  link for both the concepts in the livebooks.
 This PR btw =>
 https://github.com/kalviumcommunity/Task_Manager_and_Collaboration_Tool/pull/9

**Pull request merged**
